create database if not exists ot;
create table if not exists ot.manhattan(
                                               study String,
                                               chrom Enum8('1' = 1, '2' = 2, '3' = 3, '4' = 4, '5' = 5, '6' = 6, '7' = 7, '8' = 8, '9' = 9, '10' = 10, '11' = 11, '12' = 12, '13' = 13, '14' = 14, '15' = 15, '16' = 16, '17' = 17, '18' = 18, '19' = 19, '20' = 20, '21' = 21, '22' = 22, 'X'= 23, 'Y' = 24, 'MT'=25 ),
                                               pos UInt32,
                                               ref String,
                                               alt String,
                                               pval Float64,
                                               pval_mantissa Float64,
                                               pval_exponent Int32,
                                               odds Nullable(Float64),
                                               oddsL Nullable(Float64),
                                               oddsU Nullable(Float64),
                                               direction Nullable(String),
                                               beta Nullable(Float64),
                                               betaL Nullable(Float64),
                                               betaU Nullable(Float64),
                                               credibleSetSize Nullable(UInt64),
                                               ldSetSize Nullable(UInt64),
                                               uniq_variants UInt64,
                                               top10_genes_raw_ids Array(Nullable(String)) default [],
                                               top10_genes_raw_score Array(Float64) default [],
                                               top10_genes_coloc_ids Array(Nullable(String)) default [],
                                               top10_genes_coloc_score Array(Float64) default [],
                                               top10_genes_l2g_ids Array(Nullable(String)) default [],
                                               top10_genes_l2g_score Array(Float64) default []
) engine = MergeTree order by (study, chrom, pos, ref, alt);

insert into ot.manhattan
select
       study,
       cast(assumeNotNull(chrom) as Enum8('1' = 1, '2' = 2, '3' = 3, '4' = 4, '5' = 5, '6' = 6, '7' = 7, '8' = 8, '9' = 9, '10' = 10, '11' = 11, '12' = 12, '13' = 13, '14' = 14, '15' = 15, '16' = 16, '17' = 17, '18' = 18, '19' = 19, '20' = 20, '21' = 21, '22' = 22, 'X'= 23, 'Y' = 24, 'MT'=25 )) as chrom,
       pos,
       ref,
       alt,
       pval,
       pval_mantissa,
       pval_exponent,
       odds,
       oddsL,
       oddsU,
       direction,
       beta,
       betaL,
       betaU,
       credibleSetSize,
       ldSetSize,
       uniq_variants,
       top10_genes_raw_ids,
       top10_genes_raw_score,
       top10_genes_coloc_ids,
       top10_genes_coloc_score,
       top10_genes_l2g_ids,
       top10_genes_l2g_score
from ot.manhattan_log;