create table if not exists ot.v2d_by_chrpos
engine MergeTree partition by (chr_id) order by (chr_id, position)
as select
  assumeNotNull(chr_id) as chr_id,
  assumeNotNull(position) as position,
  assumeNotNull(ref_allele) as ref_allele,
  assumeNotNull(alt_allele) as alt_allele,
  assumeNotNull(stid) as stid,
  assumeNotNull(index_variant_id) as index_variant_id,
  r2,
  afr_1000g_prop,
  amr_1000g_prop,
  eas_1000g_prop,
  eur_1000g_prop,
  sas_1000g_prop,
  log10_abf,
  posterior_prob,
  pmid,
  pub_date,
  pub_journal,
  pub_title,
  pub_author,
  trait_reported,
  trait_efos,
  trait_code,
  trait_category,
  ancestry_initial,
  ancestry_replication,
  n_initial,
  n_replication,
  n_cases,
  assumeNotNull(if(pval = 0.,toFloat64('4.9e-323') ,pval )) as pval,
  assumeNotNull(index_variant_rsid) as index_rs_id,
  assumeNotNull(index_chr_id) as index_chr_id,
  assumeNotNull(index_position) as index_position,
  assumeNotNull(index_ref_allele) as index_ref_allele,
  assumeNotNull(index_alt_allele) as index_alt_allele,
  assumeNotNull(variant_id) as variant_id,
  assumeNotNull(rs_id) as rs_id
from ot.v2d_log;

create table if not exists ot.v2d_by_stchr
engine MergeTree partition by (chr_id) order by (stid, chr_id, position)
as select
  assumeNotNull(chr_id) as chr_id,
  assumeNotNull(position) as position,
  assumeNotNull(ref_allele) as ref_allele,
  assumeNotNull(alt_allele) as alt_allele,
  assumeNotNull(stid) as stid,
  assumeNotNull(index_variant_id) as index_variant_id,
  r2,
  afr_1000g_prop,
  amr_1000g_prop,
  eas_1000g_prop,
  eur_1000g_prop,
  sas_1000g_prop,
  log10_abf,
  posterior_prob,
  pmid,
  pub_date,
  pub_journal,
  pub_title,
  pub_author,
  trait_reported,
  trait_efos,
  trait_code,
  trait_category,
  ancestry_initial,
  ancestry_replication,
  n_initial,
  n_replication,
  n_cases,
  assumeNotNull(if(pval = 0.,toFloat64('4.9e-323') ,pval )) as pval,
  assumeNotNull(index_variant_rsid) as index_rs_id,
  assumeNotNull(index_chr_id) as index_chr_id,
  assumeNotNull(index_position) as index_position,
  assumeNotNull(index_ref_allele) as index_ref_allele,
  assumeNotNull(index_alt_allele) as index_alt_allele,
  assumeNotNull(variant_id) as variant_id,
  assumeNotNull(rs_id) as rs_id
from ot.v2d_log;

